<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2,097.00</name>
   <tag></tag>
   <elementGuidId>7f4c7e23-9a71-4491-ae4a-7410a1e3ddb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.after-price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-entry-0']/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af3cc31a-684a-483c-b4c4-f87938a345ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>after-price</value>
      <webElementGuid>dfb31383-64f2-4663-9a4b-911a06e66406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        $2,097.00
                            </value>
      <webElementGuid>36761116-09ad-4b1f-b33c-ee70ecd88fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-entry-0&quot;)/div[@class=&quot;product-price-actions&quot;]/div[@class=&quot;product-price&quot;]/div[@class=&quot;after-price&quot;]</value>
      <webElementGuid>2e096dba-2dcb-4af9-b59a-233dccc84c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-entry-0']/div[2]/div/div</value>
      <webElementGuid>f11a52d0-7bb9-471b-9158-f730e8ae6e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saber más'])[1]/following::div[3]</value>
      <webElementGuid>ff73eaf3-0aea-4f8f-8861-bc6c96fcd8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambiar plan de protección'])[1]/following::div[4]</value>
      <webElementGuid>b47efd5a-ae80-41ff-80f0-5710b0b38458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actualizar'])[1]/preceding::div[19]</value>
      <webElementGuid>cef3ba5b-ac80-4675-9e8b-c363509d3107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$2,097.']/parent::*</value>
      <webElementGuid>13bc9ce3-3722-437a-899a-544aaacb0e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div/div/div/div/div[3]/div/div/div[2]/div[2]/div/div</value>
      <webElementGuid>aa8e402d-ed4e-436b-b7e4-00cc91833591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        $2,097.00
                            ' or . = '
                        $2,097.00
                            ')]</value>
      <webElementGuid>6150f5fa-554b-4123-932a-5fa3da339448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
