<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ddad70b6-5600-4a3e-b4d5-bf137f790d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Logo-Normal.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo-Normal.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>25432533-bbfa-4746-8d5e-079e616fcd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>51febf2c-0b77-48ed-8390-c254e312fbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>1f940de7-9504-4c39-ae05-463e9a1a2b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg</value>
      <webElementGuid>08eea3ea-e0e6-4af9-8c45-de10a0d0ceb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-cartPage pageType-ContentPage template-pages-CartPageTemplate pageLabel-cart smartedit-page-uid-cartPage smartedit-page-uuid-eyJpdGVtSWQiOiJjYXJ0UGFnZSIsImNhdGFsb2dJZCI6Im9mZmljZWRlcG90Q29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9 smartedit-catalog-version-uuid-officedepotContentCatalog/Online  language-en&quot;]/main[1]/header[@class=&quot;js-mainHeader mainHeader-mx cont-fixed site-officedepot&quot;]/div[@class=&quot;content-header&quot;]/nav[@class=&quot;navigation navigation--middle js-navigation--middle&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;content-header-mobile&quot;]/div[@class=&quot;mobile__nav__row mobile__nav__row--table&quot;]/div[@class=&quot;mobile__nav__row--table-group&quot;]/div[@class=&quot;mobile__nav__row--table-row&quot;]/div[@class=&quot;hidden-xs hidden-sm js-mobile-logo container-site-header-desk&quot;]/div[@class=&quot;yCmsComponent yComponentWrapper site-logo logo-od-normal&quot;]/div[@class=&quot;banner__component banner&quot;]/a[1]/img[1]</value>
      <webElementGuid>939a7b33-d15d-4bea-b845-b638297ce52f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo-Normal.png']</value>
      <webElementGuid>b16d0da9-4243-41cb-8d08-a39bc28bcfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2d957479-3662-4f95-87ea-0c8e2138c15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Logo-Normal.png' and @alt = 'Logo-Normal.png' and @src = '/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg']</value>
      <webElementGuid>b373782a-04c7-475e-8241-6000290bb1b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
