<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gratis_lazy</name>
   <tag></tag>
   <elementGuidId>b7448d65-5c41-4ecd-a2f7-433e8a127ad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lazy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-entry-0']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78217f73-924d-4ae5-acce-9939d28c138b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>e524c4bf-c3c4-4459-87ff-9ffbc67fab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/300ftw-90130.jpg?context=bWFzdGVyfHJvb3R8MjU2NDV8aW1hZ2UvanBlZ3xhR1kxTDJnNE1DOHhNalV5TVRBMU1qVTJPVFl6TUM4ek1EQm1kSGRmT1RBeE16QXVhbkJufDc2MTljODRjNjYwNzkzMTkyYWJhNDMwMTM2ZmFkMjQ3OTk5OWQ0YzAyMjQ4ZDRiMDZkMTY0ZTJlZjIyNzI2NTQ</value>
      <webElementGuid>2311ac52-c11c-4be1-ac04-d9e6e02c6ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/medias/300ftw-90130.jpg?context=bWFzdGVyfHJvb3R8MjU2NDV8aW1hZ2UvanBlZ3xhR1kxTDJnNE1DOHhNalV5TVRBMU1qVTJPVFl6TUM4ek1EQm1kSGRmT1RBeE16QXVhbkJufDc2MTljODRjNjYwNzkzMTkyYWJhNDMwMTM2ZmFkMjQ3OTk5OWQ0YzAyMjQ4ZDRiMDZkMTY0ZTJlZjIyNzI2NTQ</value>
      <webElementGuid>34658173-8478-4388-aa37-7402f5578a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas</value>
      <webElementGuid>aca24d73-4cee-40ab-a64f-6951b81bdde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas</value>
      <webElementGuid>918b8645-67c0-47c5-ba14-a290ee5bb9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-entry-0&quot;)/div[@class=&quot;product-info&quot;]/div[@class=&quot;product-image&quot;]/a[1]/img[@class=&quot;lazy&quot;]</value>
      <webElementGuid>47367927-47db-4ee8-a901-87a0a98f168e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-entry-0']/div/div/a/img</value>
      <webElementGuid>25cc5e16-de09-4d6a-bbd7-66810f35e1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas']</value>
      <webElementGuid>7a150839-fb6d-4e4b-b3e4-281baf1ffc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>aa688fdc-3c2b-4efd-a33b-a7a1be43b01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/medias/300ftw-90130.jpg?context=bWFzdGVyfHJvb3R8MjU2NDV8aW1hZ2UvanBlZ3xhR1kxTDJnNE1DOHhNalV5TVRBMU1qVTJPVFl6TUM4ek1EQm1kSGRmT1RBeE16QXVhbkJufDc2MTljODRjNjYwNzkzMTkyYWJhNDMwMTM2ZmFkMjQ3OTk5OWQ0YzAyMjQ4ZDRiMDZkMTY0ZTJlZjIyNzI2NTQ' and @alt = 'Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas' and @title = 'Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas']</value>
      <webElementGuid>ed54795d-4478-47f4-bc17-146a809785b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
