<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_2,097.00_input_quantity_0</name>
   <tag></tag>
   <elementGuidId>7b7b1f32-2d1f-4ee4-9c3f-ac5180672544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_quantity_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_quantity_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>713475c8-61ee-4334-8c99-8d56c0062e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98c7a52b-c6fd-4116-886c-0bebe3d1a94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-update-entry-quantity-input pd-update-qty-dropdown-input</value>
      <webElementGuid>84d832da-ca67-4680-8fc4-78ce2c7632a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ed6ec75c-197b-48c0-8b83-6b1ab3bf4f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>67871</value>
      <webElementGuid>5cf7eac5-7a63-4276-852a-5a59d9ce69b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de779151-fd86-4026-8020-ccfc65408385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_quantity_0</value>
      <webElementGuid>13b1b1ef-5969-490f-b1ed-46530274d923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3a318d60-fd4d-45bd-97a2-28705b1ac11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3f88fe4a-a1a0-405a-a646-3a36b1668e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_quantity_0&quot;)</value>
      <webElementGuid>995c2785-a34e-4c36-bad3-ae0e633a09f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_quantity_0']</value>
      <webElementGuid>19a19b19-8234-4d2e-963b-e13a2f2e5bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quantity_0']/div/input</value>
      <webElementGuid>20b7f873-2b31-41c4-8f5e-3860abb75dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>008b91cd-b4bd-4d5b-9391-631c0d2bf519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_quantity_0']</value>
      <webElementGuid>3b6e5e62-9301-44bf-a725-25bd88011183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
