<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5257e597-7d38-419f-af03-399f2cfc8a3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Logo-Normal.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo-Normal.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cdb33616-00ce-4fac-9ba9-b1eb7cd9d47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>b763248d-28e9-4c17-b758-b2dfcdf513d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>617bd998-84d5-4635-94c2-457852228ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg</value>
      <webElementGuid>ac2f20b0-d629-4dbd-b33b-6c2254b4a4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-login pageType-ContentPage template-pages-LoginPageTemplate pageLabel-login smartedit-page-uid-login smartedit-page-uuid-eyJpdGVtSWQiOiJsb2dpbiIsImNhdGFsb2dJZCI6Im9mZmljZWRlcG90Q29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9 smartedit-catalog-version-uuid-officedepotContentCatalog/Online  language-en&quot;]/main[@class=&quot;login-page register&quot;]/div[@class=&quot;login-checkout-header text-center d-block w-100&quot;]/div[@class=&quot;logo-com-mx&quot;]/div[@class=&quot;yCmsComponent yComponentWrapper&quot;]/div[@class=&quot;banner__component banner&quot;]/a[1]/img[1]</value>
      <webElementGuid>20bc0c7d-d2ff-4594-93da-a492f9c394b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo-Normal.png']</value>
      <webElementGuid>dc4d38ce-4729-424f-a898-dcd69de50093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>309ee2e6-bb2e-41ad-b6ba-89f887cf93ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Logo-Normal.png' and @alt = 'Logo-Normal.png' and @src = '/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg']</value>
      <webElementGuid>ca2e40ab-0193-418d-b25e-a2edd322de57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
