<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_699.00</name>
   <tag></tag>
   <elementGuidId>eaa13d9c-3c31-4bca-bbd0-23179d8e352b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priceFormato</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='priceFormato']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a269115-1a56-4c01-b2c9-1ccd99b87ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priceFormato</value>
      <webElementGuid>539a0c42-fc02-4c63-a2e7-52918a619056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>priceDataa</value>
      <webElementGuid>6bb05afa-7cde-481d-84fb-b07b2447dfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                              $699.00</value>
      <webElementGuid>6c961d8f-1986-48ce-8700-b521421b0173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priceFormato&quot;)</value>
      <webElementGuid>77b75b19-c056-42cb-bc98-12da892fe6c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='priceFormato']</value>
      <webElementGuid>63f2e4a4-68b6-40de-bcaa-a7e08069705f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio exclusivo online'])[1]/following::div[1]</value>
      <webElementGuid>0cda22ce-0c13-449e-b2da-66c18985737e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad'])[1]/following::div[6]</value>
      <webElementGuid>ce8a935a-867a-447e-bc98-9546c6e2ba3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar meses sin intereses'])[1]/preceding::div[2]</value>
      <webElementGuid>82436400-f38d-4c96-8e8c-3a4d7e98b39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago a meses sin intereses'])[1]/preceding::div[8]</value>
      <webElementGuid>0c89109f-d182-4c6b-b2d8-c062acd9f997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$699.']/parent::*</value>
      <webElementGuid>e860e91a-7533-473f-a824-a180dd2416e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//time/div/div/div[2]/div[2]</value>
      <webElementGuid>3afed0cc-959a-497c-9525-19d891e7179f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'priceFormato' and (text() = '
                                              $699.00' or . = '
                                              $699.00')]</value>
      <webElementGuid>2144bde9-81b6-4ce4-8368-8e0d36b75f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
