<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cantidad_flecha-cantidad-mb</name>
   <tag></tag>
   <elementGuidId>dd4786a2-2525-452b-b527-1cf51d6a5c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flecha-cantidad-mb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flecha-cantidad-mb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>413ae729-f8ce-4259-b075-19c6cd29b1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flecha-cantidad-mb</value>
      <webElementGuid>61caa4c4-a654-453d-9446-4ae3b783f45b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flecha-close</value>
      <webElementGuid>819d98a3-db2a-474b-bc4f-93cb2c01a54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flecha-cantidad-mb&quot;)</value>
      <webElementGuid>65a6c590-982d-4866-a76c-b9fde5d695de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flecha-cantidad-mb']</value>
      <webElementGuid>b94262fe-26b9-42af-b887-652368ed9956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primer']/div</value>
      <webElementGuid>0a77c9a0-73a3-44d6-a6e0-2756950faa89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//time/div/div/div/div[2]/div/div</value>
      <webElementGuid>63216310-4606-4316-bc5a-f01d428cd829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flecha-cantidad-mb']</value>
      <webElementGuid>16d0262b-2287-459e-8bd2-4c0bda241ba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
