<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2,097.00</name>
   <tag></tag>
   <elementGuidId>797d39c4-4324-497b-85fb-02560128f21c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart_totalPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart_totalPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>677dbac6-d3c1-465d-9c70-30ec574f1d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart_totalPrice</value>
      <webElementGuid>cb4c3c60-8080-4f57-9b1c-b0eff0d2c9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-6 col-md-6 sub-new-ui negritaOD</value>
      <webElementGuid>f94dfbc9-1735-4ea1-9dbd-bb7069dc69f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$2,097.00</value>
      <webElementGuid>acf0759a-1003-42c9-8c0a-ebe9d68ec503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_totalPrice&quot;)</value>
      <webElementGuid>694aa09e-9585-4a34-9dce-df7acb189ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cart_totalPrice']</value>
      <webElementGuid>b34a5cd9-daea-4b98-8b99-22af552fdf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnViewCart']/div[2]/div/div[5]/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>52c92f60-1d45-46f5-9e0f-36e113b7de7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::div[1]</value>
      <webElementGuid>412b56c3-db11-44cb-8fc2-1f83ffd7ce23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>9b494dca-267b-4ed1-b48a-401ff4798d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cart_totalPrice' and (text() = '$2,097.00' or . = '$2,097.00')]</value>
      <webElementGuid>b5839c2d-7bfd-45f1-903f-4504fcf91851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
