<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo a domicilio_lazy</name>
   <tag></tag>
   <elementGuidId>37303538-bbb1-418e-b325-8362537356e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lazy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productListExpressCheckout']/div/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3b51a41a-d0cc-4479-947f-c62704e0170e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>db818454-a0ce-4ef3-b7e5-11ec24fb9087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/96ftw-90130.jpg?context=bWFzdGVyfHJvb3R8MzQ5MXxpbWFnZS9qcGVnfGFETTJMMmczWkM4eE1qVXlNVEExTWpRek9EVTFPQzg1Tm1aMGQxODVNREV6TUM1cWNHY3wyNjc0ZjA5ODNmOWUxNTE4MDk1NTA4ODVmZjkzZjM0YmM0NWZhNTdiNWM0ZmMyZDFmZGE2ODZiMWVjZDM0Yjk2</value>
      <webElementGuid>66e29100-d027-44cb-9ec4-bd1544cf5e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/medias/96ftw-90130.jpg?context=bWFzdGVyfHJvb3R8MzQ5MXxpbWFnZS9qcGVnfGFETTJMMmczWkM4eE1qVXlNVEExTWpRek9EVTFPQzg1Tm1aMGQxODVNREV6TUM1cWNHY3wyNjc0ZjA5ODNmOWUxNTE4MDk1NTA4ODVmZjkzZjM0YmM0NWZhNTdiNWM0ZmMyZDFmZGE2ODZiMWVjZDM0Yjk2</value>
      <webElementGuid>4743ad64-86ec-4b1d-a642-8e7ccd534e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas</value>
      <webElementGuid>63817d4a-c445-4da8-8378-b59d51f319fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas</value>
      <webElementGuid>e99d82c0-3779-4383-abcc-63b925662d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productListExpressCheckout&quot;)/div[@class=&quot;order-item-container item-deliveryOrderGroups&quot;]/div[@class=&quot;col-xs-12 cart-items-content border&quot;]/div[@class=&quot;summary-list-items-exp&quot;]/div[@class=&quot;productImage-exp col-xs-5 col-md-4 container-center-items&quot;]/a[1]/img[@class=&quot;lazy&quot;]</value>
      <webElementGuid>cf08042d-126b-4eb2-bd47-4ea269e7f438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productListExpressCheckout']/div/div[2]/div/div/a/img</value>
      <webElementGuid>f8c0c6e1-d416-4f32-8c3c-5916327f6699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas']</value>
      <webElementGuid>61cc27e1-d677-49f3-89c9-63c4a904fff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>f7be911d-4fa8-4004-aa02-6911b54a0fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/medias/96ftw-90130.jpg?context=bWFzdGVyfHJvb3R8MzQ5MXxpbWFnZS9qcGVnfGFETTJMMmczWkM4eE1qVXlNVEExTWpRek9EVTFPQzg1Tm1aMGQxODVNREV6TUM1cWNHY3wyNjc0ZjA5ODNmOWUxNTE4MDk1NTA4ODVmZjkzZjM0YmM0NWZhNTdiNWM0ZmMyZDFmZGE2ODZiMWVjZDM0Yjk2' and @alt = 'Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas' and @title = 'Caja de Papel Ecológico Tamaño Carta Earth Pact Blanco 5000 hojas']</value>
      <webElementGuid>0944a678-e9ce-453d-bab0-e813b7992e89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
