<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(ej. departamento 3 edificio A, puert_f49e7a</name>
   <tag></tag>
   <elementGuidId>a060ff9e-12c1-469a-a4fd-8c089297bcef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='reference'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reference</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6517a7b-df82-4e6e-aff6-ab3f12ffb266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>405acbb1-7d45-4805-8230-1af891cd359f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>15f76cba-8e7c-4cdc-afa8-5347e6d10b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reference-formatter form-control</value>
      <webElementGuid>bb76f44d-7f2f-4175-9877-a491cb14d524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; return charSpecial(event)</value>
      <webElementGuid>078c6b39-3563-488a-87d1-fc679773e159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>&quot;Agrega referencias o instrucciones específicas para que podamos ubicarte fácilmente.&quot;</value>
      <webElementGuid>660a2e6b-a808-44c1-a365-4584f038215c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ce7c88e-f915-4338-b30e-94add64758c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference&quot;)</value>
      <webElementGuid>88cb18e3-695f-45a1-8a5a-c754f1cffd97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference']</value>
      <webElementGuid>09664861-402b-46cf-bb85-103435b7dc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i18nAddressForm']/div/div[3]/div[12]/div/div/input</value>
      <webElementGuid>93723c7d-68cb-4bf2-a188-8cd3b9065425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/input</value>
      <webElementGuid>f1aa640a-61e7-4e20-9e60-1504d47d4139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reference' and @name = 'reference' and @placeholder = '&quot;Agrega referencias o instrucciones específicas para que podamos ubicarte fácilmente.&quot;' and @type = 'text']</value>
      <webElementGuid>6ab5642c-041e-475c-83c6-8a19d7f69e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
