<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pago a contra entrega_paypos</name>
   <tag></tag>
   <elementGuidId>c4865ef5-34d6-4f00-8f5b-9562a6379891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paypos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paypos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1250604-5f4a-49d3-84ec-88de227ce0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9776decb-e0e5-4bf7-b208-046845665ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypos</value>
      <webElementGuid>6ef95512-3489-483a-9fec-712099a7be23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name-radio-payment</value>
      <webElementGuid>e95a99e8-27b2-4137-85d2-e8d9e4dd5086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paymentMethod-button</value>
      <webElementGuid>48613fd4-f944-4003-8996-2c6fa34811d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypos&quot;)</value>
      <webElementGuid>f7dccbaa-92d3-452a-bf79-a5327c137047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paypos']</value>
      <webElementGuid>b5868ccd-ef5c-41d4-b893-24f656b8075a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='label_paypos']/input</value>
      <webElementGuid>6e0a2018-ac22-475e-9991-0c072deb3d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/label/input</value>
      <webElementGuid>b139853c-3a24-4c7e-9e25-4d94f88fed45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'paypos' and @name = 'name-radio-payment']</value>
      <webElementGuid>c488b5d7-05e0-45c7-ba65-586c4240cb52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
