<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__streetName</name>
   <tag></tag>
   <elementGuidId>4b99620c-f56c-4c2c-a0e7-f429bd03d6af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#streetName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='streetName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5b6613b-394b-4704-9aea-ce8dbf09c917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streetName</value>
      <webElementGuid>34a25b45-ec34-4d11-9fe8-c818b4f2082c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>streetName</value>
      <webElementGuid>31dab11e-08bd-4ac9-b284-919d68f1c97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text form-control</value>
      <webElementGuid>c3fb378a-9781-4b72-a689-d0b29eed9623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; return charSpecial(event)</value>
      <webElementGuid>ca7d8f50-c49e-49f6-9a10-2bf9f4c4f802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e5845da-6a97-4e97-8387-c150947ea9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>--</value>
      <webElementGuid>56e101cb-5ff5-4cc2-86d8-b87516b0130b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streetName&quot;)</value>
      <webElementGuid>fef4c42d-e25a-4713-a398-ef9e5a666f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='streetName']</value>
      <webElementGuid>1076dd49-fb8a-411c-9f21-e5b683440c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i18nAddressForm']/div/div[3]/div[5]/div/div/input</value>
      <webElementGuid>1f6819af-2097-476b-b217-1e44b863f529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div/div/input</value>
      <webElementGuid>ee19db6d-af02-4286-a453-078ac99b57d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'streetName' and @name = 'streetName' and @type = 'text']</value>
      <webElementGuid>78958122-f07f-437d-a218-e997241517a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
