<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifica tu ubicacin_saveAddressInMyA_91c621</name>
   <tag></tag>
   <elementGuidId>d1b3afda-856c-4d7a-9b4b-c9cca0f69b2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveAddressInMyAddressBook</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saveAddressInMyAddressBook']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b971ea86-292b-4c99-9a4f-78403b14a030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveAddressInMyAddressBook</value>
      <webElementGuid>36ba5fc7-8173-4242-8749-f22917540c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>saveInAddressBook</value>
      <webElementGuid>91f731f1-eec7-4509-a7b3-5ed9eaf087d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputcss</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0c5f5a4d-d181-48b0-ad5b-0a9ab320a3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>786557a5-ac02-49fa-a146-760b698a6d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3c264cbc-6232-4f0b-8427-f6612cca1b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveAddressInMyAddressBook&quot;)</value>
      <webElementGuid>c89057bb-f798-4554-b9e1-8b5620c334cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saveAddressInMyAddressBook']</value>
      <webElementGuid>7daf22b9-6cff-46a8-86ef-9a3f89d2cdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i18nAddressForm']/div/div[3]/div[14]/div[3]/div/label/input</value>
      <webElementGuid>9d5b07b2-08b4-4fc3-bc42-2d9237972ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>1b42099f-ee6e-4021-aebd-cb15d511857d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'saveAddressInMyAddressBook' and @name = 'saveInAddressBook' and @type = 'checkbox']</value>
      <webElementGuid>eec4898d-ef67-4357-91f6-0b16bcf2ae2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
