<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continuar</name>
   <tag></tag>
   <elementGuidId>776011e2-213d-4573-9789-843591e89a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cboxLoadedContent']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dca2b910-2ae1-4e0c-af0a-c42459ab89b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-button</value>
      <webElementGuid>fa0db431-8d3a-4fb2-94b9-8570a7f1882d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>f68aa2ea-d0d2-4f3e-baeb-1e43a69db701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboxLoadedContent&quot;)/button[@class=&quot;content-button&quot;]/span[@class=&quot;text-button&quot;]</value>
      <webElementGuid>b1eb402d-e799-4693-8638-0b8bb4d800c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cboxLoadedContent']/button/span</value>
      <webElementGuid>56faa3f5-368f-4ac3-93b1-065b4d2f3543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report a map error'])[1]/following::span[1]</value>
      <webElementGuid>110c5a09-a591-474a-bb43-c0a047616346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms'])[1]/following::span[1]</value>
      <webElementGuid>3efd995a-35ec-4b79-b99f-e0adff17aeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BESbswy'])[1]/preceding::span[2]</value>
      <webElementGuid>ad1e7248-c11d-4182-bc27-6936357fcac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>677c1016-333c-4762-a7e2-912e494828c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>d0260698-100d-41dc-9dc0-4749fe1351b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>76420d0f-e878-4d99-9be0-d3975045516c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
