<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ver detalle</name>
   <tag></tag>
   <elementGuidId>7eaffbbb-0c28-450e-8d16-f77ee7b2f563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-turquesa.font-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='d1']/div/div/div/div/fieldset/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e4437c1-6ebc-462f-80b6-be3b2e1fff29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/officedepot/en/my-account/order/1703153071</value>
      <webElementGuid>14437389-ca65-45ed-9b69-0389719fec34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-turquesa font-bold</value>
      <webElementGuid>f5801199-eb30-4d53-bf89-566e11fee731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver detalle</value>
      <webElementGuid>930b2f3d-dedd-4b76-b937-3824b4bd26b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d1&quot;)/div[@class=&quot;account-orderhistory&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-4 account-overview-table&quot;]/div[@class=&quot;row orderhistory-list-table responsive-table&quot;]/fieldset[@class=&quot;col-xs-12 accountContentPane fieldset-orderHistory fieldset-orderStatus-HPPY&quot;]/div[@class=&quot;col-xs-12 container-BtnOptionsOrder&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 container-BtnDetails&quot;]/a[@class=&quot;btn btn-turquesa font-bold&quot;]</value>
      <webElementGuid>d6bf9abd-a2dc-454e-8ce0-c35c40ca34df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='d1']/div/div/div/div/fieldset/div[2]/div/div/a</value>
      <webElementGuid>b35d9428-3a26-41ec-9248-3f642e1a202c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ver detalle')]</value>
      <webElementGuid>bc4792f1-15e6-46e2-8c0e-139000a1cab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pedido el 30 abr. 2026 04:04'])[1]/following::a[1]</value>
      <webElementGuid>0f4aad78-a4d2-46ab-8fc0-b5efd5d105b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,097.00'])[1]/following::a[1]</value>
      <webElementGuid>4ea753aa-285d-4a8b-ab18-bcd1fa03df56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordenar por:'])[1]/preceding::a[1]</value>
      <webElementGuid>6de51725-ed45-4944-8474-20b178f7828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date:'])[1]/preceding::a[1]</value>
      <webElementGuid>55d119f7-3c6f-47c7-adb6-74021b1ebd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver detalle']/parent::*</value>
      <webElementGuid>eafaf834-0439-4b95-80d3-8fdf79f19931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/officedepot/en/my-account/order/1703153071')]</value>
      <webElementGuid>5edede10-baf8-4e93-8a11-eccaf27c9a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div/a</value>
      <webElementGuid>76378b20-a39f-43ef-bf2d-ba7ba4ddd416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/officedepot/en/my-account/order/1703153071' and (text() = 'Ver detalle' or . = 'Ver detalle')]</value>
      <webElementGuid>dfbfb418-6a7d-4533-806c-6cd82e9075f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
