<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e0ece141-1514-4926-a850-5ae9580c3959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Celulares&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filaDeCategorias']/div/div/div/div[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Celulares Celulares&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>49f8d747-6210-4624-a339-72bfb7822bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Celulares</value>
      <webElementGuid>75e2a441-6f51-4b90-9a53-802df585ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.officedepot.com.mx/medias/celulares-02.png?context=bWFzdGVyfHJvb3R8MjI5MzV8aW1hZ2UvcG5nfGFHRTJMMmc0WVM4eE16QXhNREEzT1RFNE5qazNOQzlqWld4MWJHRnlaWE10TURJdWNHNW58MDY5NmVmOTkwZjQzMmVmNGEzNWMxN2I2YzZlM2ZlN2I3NDk1OWI1ZGVmODExM2RiZmUyOTZlMDNlOTY2Mzc0MQ</value>
      <webElementGuid>d7f380bd-2194-4cf5-ba8f-2b29358a1b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filaDeCategorias&quot;)/div[@class=&quot;contCategorias&quot;]/div[@class=&quot;swiper swiperCategorias swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide&quot;]/a[1]/img[1]</value>
      <webElementGuid>a13e9659-0d03-4043-80c0-27483cd54e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filaDeCategorias']/div/div/div/div[4]/a/img</value>
      <webElementGuid>85143f49-0d4e-4010-bcc3-2b27b96f80bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Celulares']</value>
      <webElementGuid>fe1de30b-7419-4f4d-99db-1d123a44b0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>ca0ad2ab-ff06-437c-b70e-806c1d38aaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Celulares' and @src = 'https://www.officedepot.com.mx/medias/celulares-02.png?context=bWFzdGVyfHJvb3R8MjI5MzV8aW1hZ2UvcG5nfGFHRTJMMmc0WVM4eE16QXhNREEzT1RFNE5qazNOQzlqWld4MWJHRnlaWE10TURJdWNHNW58MDY5NmVmOTkwZjQzMmVmNGEzNWMxN2I2YzZlM2ZlN2I3NDk1OWI1ZGVmODExM2RiZmUyOTZlMDNlOTY2Mzc0MQ']</value>
      <webElementGuid>15db37e8-b1e1-4613-a8f7-ec3c88c2bf94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
