<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_30,947.65</name>
   <tag></tag>
   <elementGuidId>83aa7e60-18eb-4426-bb98-c9b7cb53ca99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-entry-0']/div[3]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.after-price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#product-entry-0 >> internal:text=&quot;$30,947.65&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>475f6761-3885-49a4-9e49-c2744fd1ab6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>after-price</value>
      <webElementGuid>2b9878d4-b6e3-47fd-bb3c-93ae6c19fd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        $30,947.65
                            </value>
      <webElementGuid>af1e156b-910e-4d0f-92cb-b5bfb621b8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-entry-0&quot;)/div[@class=&quot;product-price-actions&quot;]/div[@class=&quot;product-price&quot;]/div[@class=&quot;after-price&quot;]</value>
      <webElementGuid>e29bb791-0bf2-4f67-8266-bd6425fd01ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-entry-0']/div[3]/div/div[2]</value>
      <webElementGuid>bb91f0a3-8a4c-4089-90d1-200163b4492e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descuento en garantía - Programa de Lealtad'])[1]/following::div[5]</value>
      <webElementGuid>31a92412-ed8b-4daf-8673-db22ade639dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,469.00'])[2]/preceding::div[1]</value>
      <webElementGuid>1fd03744-ab89-461c-bb68-cca8f83a37fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,948.65'])[3]/preceding::div[2]</value>
      <webElementGuid>718eb81e-2bc0-4cd3-a913-1efd6cc87b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$30,947.']/parent::*</value>
      <webElementGuid>b326ebd4-4319-4975-a5a2-d8ad21e244d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]</value>
      <webElementGuid>ef86a47d-d461-4ce2-b12c-08fb132e0be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        $30,947.65
                            ' or . = '
                        $30,947.65
                            ')]</value>
      <webElementGuid>ce8e2e97-5c9b-47f4-b81d-37930a60999c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
