<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Por favor ingresa un correo vlido_j_p_38a518</name>
   <tag></tag>
   <elementGuidId>815b42da-645d-4fac-9b19-c9b5ffe8e9ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#j_passwordexpress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='j_passwordexpress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86f15dfa-b05e-42c7-9053-353809c53e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_passwordexpress</value>
      <webElementGuid>abab45d6-5c83-488b-922f-6e8204f51b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_password</value>
      <webElementGuid>a67b6956-9783-4d0e-ae97-713b369df2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-material font-medium  d-block w-100</value>
      <webElementGuid>3e49c194-ec79-4ef2-97c8-6a773baf485d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{6,}</value>
      <webElementGuid>1eaefef4-f5a9-418b-8a57-3ef34bbfd8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d5a9a1d3-fe76-4000-ad1a-55a2cab9e9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>67ddf73f-6a95-4177-9d94-2f62331ee1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9ebd29e9-933c-47f6-8641-f7b156ccf1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03c31341-aaac-4429-bef9-d0fa7c766266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>newpassword</value>
      <webElementGuid>f888b54b-c0a7-4be8-8698-467ef4a4dc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_passwordexpress&quot;)</value>
      <webElementGuid>eaf40554-2426-4fe9-810a-dae42e10bc79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_passwordexpress']</value>
      <webElementGuid>23f55899-ee45-4a3f-a236-4d12d1705928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[2]/input</value>
      <webElementGuid>16724020-000b-45ec-84d1-4be8a9185228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>89de3dea-6bf5-4634-8368-fc375a00b2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_passwordexpress' and @name = 'j_password' and @type = 'password']</value>
      <webElementGuid>a1fd521a-1cef-4064-aa5a-b5b97fa8a374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
