<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_grid_select-heart-od heart-noanonym-od</name>
   <tag></tag>
   <elementGuidId>99d1ba05-3bae-4d13-9e99-ac429caf6c46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select-heart-od.heart-noanonym-od</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='heart-100253460']/buttom/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5229158-adc2-4d73-8870-ce33f9648050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-heart-od heart-noanonym-od</value>
      <webElementGuid>8e941e7e-a290-479a-afb2-2129f0936b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sku</name>
      <type>Main</type>
      <value>100253460</value>
      <webElementGuid>09aad1b4-dafa-4268-9fa5-4ff55105c4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Laptop Asus Vivobook 15 Intel Core i5 8GB RAM 512GB SSD 15.6 pulgadas</value>
      <webElementGuid>42373613-b149-4a80-a0ee-da75e2fe0764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-catego</name>
      <type>Main</type>
      <value>laptops y macbook</value>
      <webElementGuid>cc8c7d16-c55b-46b4-b33f-5bb0677d9038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-marc</name>
      <type>Main</type>
      <value>ASUS</value>
      <webElementGuid>d62565c1-c34b-4a69-87cd-e8f4e2860cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-precio</name>
      <type>Main</type>
      <value>13299.0</value>
      <webElementGuid>b85f8f26-672f-43ab-9c5b-be4a4325797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heart-100253460&quot;)/buttom[@class=&quot;dataheart btnWishlist&quot;]/div[@class=&quot;select-heart-od heart-noanonym-od&quot;]</value>
      <webElementGuid>41002584-6d62-4aa7-a6ba-19d2f649c952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='heart-100253460']/buttom/div</value>
      <webElementGuid>a7507e67-9754-4a31-af04-75d59342355d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//buttom/div</value>
      <webElementGuid>dc6cc035-e45c-453c-9394-82f6be350d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
