<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_19,339.00</name>
   <tag></tag>
   <elementGuidId>1eddd311-5365-487d-b549-18c3144f47a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prices-for100271182 > div.discountedPrice-grid.cont-price-grid.bp-original</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prices-for100271182']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>650fb227-dfae-4ef5-9889-a1119610edeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>discountedPrice-grid cont-price-grid bp-original</value>
      <webElementGuid>c7bcc2fd-b2b7-4e7d-904a-7276c6843caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                $19,339.00
    </value>
      <webElementGuid>0d2a1827-dbcf-46eb-b034-3b88a3a4910c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prices-for100271182&quot;)/div[@class=&quot;discountedPrice-grid cont-price-grid bp-original&quot;]</value>
      <webElementGuid>b46b2b62-f56f-4742-b09f-3cd2ecfdda8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prices-for100271182']/div</value>
      <webElementGuid>434d8e20-30f3-4470-8ef1-38ec4d4903cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agotado'])[3]/following::div[3]</value>
      <webElementGuid>5dada4f7-577f-4389-805a-5739adaf51c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop HP OmniBook 5 Snapdragon X 16GB RAM 512GB 14 pulgadas OLED'])[1]/following::div[5]</value>
      <webElementGuid>8632b6e9-6286-4506-8836-00bc5874679c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='grid'])[5]/preceding::div[14]</value>
      <webElementGuid>382b2f08-bd60-4f4d-b4d1-f66c3a807c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$19,339.']/parent::*</value>
      <webElementGuid>79d749cf-3eee-40f8-a23c-3760e70a3933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/a[3]/div[3]/div[2]/div[2]/div/div</value>
      <webElementGuid>d70b26aa-18bc-4ef1-a8cb-7554fa8a3d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                $19,339.00
    ' or . = '
                $19,339.00
    ')]</value>
      <webElementGuid>a18663a4-7c4a-456c-8487-f36280d19529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
