<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Iniciar sesin</name>
   <tag></tag>
   <elementGuidId>30410eec-bc3b-40cf-a6d6-cc1dca48ef46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginButtonMaterial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='loginButtonMaterial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a43b4259-4ee4-4e25-aa2e-cd162b8d03e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27b5d8fb-5195-428d-85b9-09d4e28473fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginButtonMaterial</value>
      <webElementGuid>cf10474f-f55e-42a8-8bab-5ffccd087ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit d-block w-100 btn btn-primary-theme font-bold</value>
      <webElementGuid>e3d33a28-a160-4664-8f17-5d1e9f841173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						Iniciar sesión</value>
      <webElementGuid>6f2d8266-6102-459b-ac7c-799b183603cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginButtonMaterial&quot;)</value>
      <webElementGuid>c202f506-6894-429b-bf9e-11f019f6ac19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='loginButtonMaterial']</value>
      <webElementGuid>8a242167-428d-4c00-8ecb-f9650ebe9b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/button</value>
      <webElementGuid>c264396b-66d0-4e86-8833-b9c68370947c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste tu contraseña?'])[1]/following::button[1]</value>
      <webElementGuid>51effde1-3ab4-42bb-ad1f-c7babe8abc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La contraseña no coincide. Intenta de nuevo'])[1]/following::button[1]</value>
      <webElementGuid>392504cb-fd5d-4771-a41a-02c5d2b25e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/preceding::button[1]</value>
      <webElementGuid>ba7d5042-bace-4ae3-aab1-609b23961512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear cuenta'])[1]/preceding::button[1]</value>
      <webElementGuid>4a8d26c2-a0b2-4586-b5a9-243da29765a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>713eb417-8bda-4279-bfdf-82162791c81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'loginButtonMaterial' and (text() = '
						Iniciar sesión' or . = '
						Iniciar sesión')]</value>
      <webElementGuid>2cd1e713-bb13-47c4-86c8-68b7f26fd0d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
