<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>8ac9e30a-6b27-4307-8b67-c2e80a83a2a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;logo-mobile&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='logo-mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a2868ba-08b1-4035-a77b-1d739ad794ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_ui/responsive/theme-officedepot/images/logo-white-mobile.svg</value>
      <webElementGuid>079262a6-fa8c-4003-a65f-d142974e0851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo-mobile</value>
      <webElementGuid>edb406dd-6392-44e7-acde-ace427c5dd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-login pageType-ContentPage template-pages-LoginPageTemplate pageLabel-login smartedit-page-uid-login smartedit-page-uuid-eyJpdGVtSWQiOiJsb2dpbiIsImNhdGFsb2dJZCI6Im9mZmljZWRlcG90Q29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9 smartedit-catalog-version-uuid-officedepotContentCatalog/Online  language-en&quot;]/main[@class=&quot;login-page login&quot;]/div[@class=&quot;login-checkout-header text-center d-block w-100&quot;]/div[@class=&quot;logo-no-com-mx&quot;]/a[1]/img[1]</value>
      <webElementGuid>d14d78e7-f0a4-4a96-881b-dd31bf7e7e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo-mobile']</value>
      <webElementGuid>49979890-e8db-4ebe-b0e2-daef447b7c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>aa11e567-163e-477a-8ff2-dc4f552232f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_ui/responsive/theme-officedepot/images/logo-white-mobile.svg' and @alt = 'logo-mobile']</value>
      <webElementGuid>791596d5-0a54-4a6e-a913-89cfe98eee5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
