<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Iniciar sesin_usernamelogin</name>
   <tag></tag>
   <elementGuidId>c1dd4d0d-c291-4995-b62f-88ae19953a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usernamelogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usernamelogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e200ef2-f6a6-4890-9bd8-d7c5eef465a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usernamelogin</value>
      <webElementGuid>b06f1798-2db3-472a-ad8c-15016c808e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_username</value>
      <webElementGuid>0e9c309c-ce69-488a-b127-7b2bfaf90c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-material font-medium  d-block w-100</value>
      <webElementGuid>ebe0423c-387f-43a8-a59d-fc7bcaa40c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z0-9]{2,}$</value>
      <webElementGuid>ce6a738f-5465-441e-9be1-12493d84d31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0980e19b-8de1-4b25-bd08-7a103d5504c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f8b44736-ee85-47ae-ad66-3ff94168a6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>usernamelogin-list</value>
      <webElementGuid>5d8051ef-7ad6-48b2-98bd-c0c5bd3c21c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4e235013-40e0-47ea-94a5-e5b4d1dfdcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>053d35ae-029a-46d3-9e3d-b6bdf3a7a09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>h</value>
      <webElementGuid>fd8cd94a-16b0-4ace-8bb6-e421e5fbb6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b95fc6f-0e82-4d4a-a0f4-e85951528356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernamelogin&quot;)</value>
      <webElementGuid>525deab4-ab25-421d-b4ce-9a3ec98e85af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usernamelogin']</value>
      <webElementGuid>406afa0e-2878-47ed-947c-c85d7e079ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div/input</value>
      <webElementGuid>b30465a1-4fba-4d01-8c59-2b9599083939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f211ac81-cab6-4b3f-a85f-2ee825875548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'usernamelogin' and @name = 'j_username' and @type = 'email']</value>
      <webElementGuid>13c05f29-c3e7-40b2-92a2-f308606ec645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
