<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Por favor ingresa un correo vlido_j_p_38a518</name>
   <tag></tag>
   <elementGuidId>8e903d52-efa4-4bf3-badc-cad718a62ee0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#j_passwordexpress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='j_passwordexpress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24037380-ea2b-4a6d-8642-0b34dba3ab88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_passwordexpress</value>
      <webElementGuid>6f0fbec8-65d3-47fd-8c64-399c3122e66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_password</value>
      <webElementGuid>ce85d0db-52ab-411c-8de5-dbe69e41ec54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-material font-medium  d-block w-100</value>
      <webElementGuid>b0579a65-3fb8-487b-9ae7-c8348a84c4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.{6,}</value>
      <webElementGuid>0ec0e521-3ab9-4d40-812c-1414da81b388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18e21622-ae92-4637-bf5f-d725dd42c1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>466ee019-784b-4206-bfad-d992ccea2d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>767211bc-5ac7-4813-b0c4-ffc4bd7918eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04bbbcd8-62f7-4cda-adb9-9c85bbff43ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>newpassword</value>
      <webElementGuid>5321fb8c-51c5-418a-9bed-7dd6a983d131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_passwordexpress&quot;)</value>
      <webElementGuid>37c85e67-b5f1-4f08-933a-a7bf19e2b822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_passwordexpress']</value>
      <webElementGuid>77e59b78-34d1-405c-b399-38e8ae5463e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[2]/input</value>
      <webElementGuid>1561ef05-3275-43a3-ad31-1eb035a34ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3d2a12bb-d791-4a2d-a3d9-a8a388e38fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_passwordexpress' and @name = 'j_password' and @type = 'password']</value>
      <webElementGuid>55183865-c5d2-419a-aa5c-3cf3a24862cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
