<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__view-password</name>
   <tag></tag>
   <elementGuidId>53e977cc-cfd2-4c39-b9f8-af22814eee54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.view-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>00351f76-d65d-4265-b131-8d4f2c0d8167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>view-password</value>
      <webElementGuid>44a31152-a16b-4ea5-9f7a-644c2bd42d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/div[@class=&quot;input-group-material&quot;]/span[@class=&quot;view-password&quot;]</value>
      <webElementGuid>973d37fc-6eb2-49a5-ab11-2521cb6c555e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[2]/span</value>
      <webElementGuid>3bb71e4f-bf35-4dff-8c92-ccc76d732aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>a1738c8d-f2a4-41a0-bb82-3cbd99850505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
