<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e4b48a09-73ae-43d1-8547-7f88f1da5eb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Logo-Normal.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo-Normal.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logo-Normal.png&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a7d78d6-1354-45fc-806c-6161d22a396a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>c3971e8c-0856-4ea5-84ef-fe7c95f32453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>b28a9ddf-24ea-43ea-abea-1e54ea7d2043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg</value>
      <webElementGuid>092aa879-bba9-4475-905d-088aab05285c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-productDetails pageType-ProductPage template-pages-product-productLayout2Page  smartedit-page-uid-productDetails smartedit-page-uuid-eyJpdGVtSWQiOiJwcm9kdWN0RGV0YWlscyIsImNhdGFsb2dJZCI6Im9mZmljZWRlcG90Q29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9 smartedit-catalog-version-uuid-officedepotContentCatalog/Online  language-en&quot;]/main[1]/header[@class=&quot;js-mainHeader mainHeader-mx cont-fixed site-officedepot&quot;]/div[@class=&quot;content-header&quot;]/nav[@class=&quot;navigation navigation--middle js-navigation--middle&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;content-header-mobile&quot;]/div[@class=&quot;mobile__nav__row mobile__nav__row--table&quot;]/div[@class=&quot;mobile__nav__row--table-group&quot;]/div[@class=&quot;mobile__nav__row--table-row&quot;]/div[@class=&quot;hidden-xs hidden-sm js-mobile-logo container-site-header-desk&quot;]/div[@class=&quot;yCmsComponent yComponentWrapper site-logo logo-od-normal&quot;]/div[@class=&quot;banner__component banner&quot;]/a[1]/img[1]</value>
      <webElementGuid>17124495-507a-4173-9960-9f56815612c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo-Normal.png']</value>
      <webElementGuid>9ec0ae27-378f-43b0-9a7f-8ebb7f4fdb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>dccc59bd-06ec-4885-b152-fee02ac8d20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Logo-Normal.png' and @alt = 'Logo-Normal.png' and @src = '/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg']</value>
      <webElementGuid>fae516e7-9177-4521-9a7e-01ec6c55cfe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
