<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PDP_DiscountPrice</name>
   <tag></tag>
   <elementGuidId>0872f86b-3d69-4150-8ce4-f219969cd5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priceFormato</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='priceFormato']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#priceFormato</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8568e5c-75cf-4b68-a47d-b6d604a6f4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priceFormato</value>
      <webElementGuid>4a72b729-8177-4836-a398-71ff2e67c928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>priceDataa</value>
      <webElementGuid>df22510c-f538-4f8e-8d46-af0d1e21122c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    $29,999.00</value>
      <webElementGuid>18d9451a-007a-47e6-8109-8f9f835eb26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priceFormato&quot;)</value>
      <webElementGuid>3772f89c-3de2-4a0e-8d95-eaafd9e995a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='priceFormato']</value>
      <webElementGuid>68b964ff-1825-4292-9120-3261e406ef58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio exclusivo online'])[1]/following::div[4]</value>
      <webElementGuid>55878cc8-6a97-456b-84ba-6eb3b2ee8854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar meses sin intereses'])[1]/preceding::div[2]</value>
      <webElementGuid>0a8251e6-2500-4119-9ba4-2380c7b891c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago a meses sin intereses'])[1]/preceding::div[8]</value>
      <webElementGuid>490f50d7-4e4d-4d1f-827b-a5d3438322e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$29,999.00']/parent::*</value>
      <webElementGuid>be8cab8b-2668-4ba4-929a-aaee83eee36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//time/div/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>cb50fb2b-094b-40da-8fe3-aa68529c74c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'priceFormato' and (text() = '
                                                    $29,999.00' or . = '
                                                    $29,999.00')]</value>
      <webElementGuid>13ee43f4-51c8-4f37-b63a-68433e30137a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
