<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6e16de59-75b9-4f55-ba7b-9c828fe37d79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Logo-Normal.png&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Logo-Normal.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aa5a810f-4cd1-4d81-a534-4ed3d098cb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>03787fa0-2839-412a-b0a8-f0493c4728c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo-Normal.png</value>
      <webElementGuid>74a315ec-3676-4819-87a3-ed2f7e703583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg</value>
      <webElementGuid>37251b38-4b29-4da4-875c-f93de364f627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-shoppingLists pageType-ContentPage template-pages-shoppinglists-shoppingListsLayoutPage pageLabel-shoppingLists smartedit-page-uid-shoppingLists smartedit-page-uuid-eyJpdGVtSWQiOiJzaG9wcGluZ0xpc3RzIiwiY2F0YWxvZ0lkIjoib2ZmaWNlZGVwb3RDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0= smartedit-catalog-version-uuid-officedepotContentCatalog/Online  language-en&quot;]/main[1]/header[@class=&quot;js-mainHeader mainHeader-mx cont-fixed site-officedepot&quot;]/div[@class=&quot;content-header&quot;]/nav[@class=&quot;navigation navigation--middle js-navigation--middle&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;content-header-mobile&quot;]/div[@class=&quot;mobile__nav__row mobile__nav__row--table&quot;]/div[@class=&quot;mobile__nav__row--table-group&quot;]/div[@class=&quot;mobile__nav__row--table-row&quot;]/div[@class=&quot;hidden-xs hidden-sm js-mobile-logo container-site-header-desk&quot;]/div[@class=&quot;yCmsComponent yComponentWrapper site-logo logo-od-normal&quot;]/div[@class=&quot;banner__component banner&quot;]/a[1]/img[1]</value>
      <webElementGuid>6d00cf17-5312-46ef-8e21-9de282c2a79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo-Normal.png']</value>
      <webElementGuid>467129f7-01c5-4be9-9c60-9f7beb405927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>77eb34f2-925f-4f86-a08f-60dde9e24044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Logo-Normal.png' and @alt = 'Logo-Normal.png' and @src = '/medias/Logo-Normal.png?context=bWFzdGVyfGltYWdlc3wxNDA3fGltYWdlL3BuZ3xhRGxrTDJnNVlTOHhNamcxT1RFNU5EQXhOVGMzTkM5TWIyZHZMVTV2Y20xaGJDNXdibWN8ZWRjMTcxZDcyZjRmZTBlMGVlNDkwZGEyY2M4NzRjMmE2NDk0ZjJhOWNhNGVjOTgwMjdjMmY3MWRiNWMyODk1Mg']</value>
      <webElementGuid>bf9b4b04-6c3b-45eb-bd3e-500760fef83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
