<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5bf9877f-b73a-43fe-93dd-ae1f9067210d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logo-express-checkout-2 > div > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo-express-checkout-2']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a90b9ca5-7005-42d7-881c-69caacc7c6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_ui/responsive/theme-officedepot/images/express-checkout/logo-OD.png</value>
      <webElementGuid>d0cb64d1-156a-4be4-bad7-bff1938cb884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-express-checkout-2&quot;)/div[1]/a[1]/img[1]</value>
      <webElementGuid>6bdd7662-9d11-4b89-8f64-5ed50a32f8df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo-express-checkout-2']/div/a/img</value>
      <webElementGuid>0e1d5da7-5eb9-4249-8bea-1b64c2e37fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/a/img</value>
      <webElementGuid>7a1eb8ff-bed9-4a5f-83ae-299a803c011c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_ui/responsive/theme-officedepot/images/express-checkout/logo-OD.png']</value>
      <webElementGuid>b076bf4b-4c61-472c-8951-b00fe3a1c930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
