<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Agrega tu ubicacin para mejorar la e_49fd67</name>
   <tag></tag>
   <elementGuidId>453f2d02-cad1-43bd-9807-034ecf2e2b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js_search_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js_search_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ebafc88-4a67-4454-bba4-9d75f7e45607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link js_search_button</value>
      <webElementGuid>8aee0189-3b4d-47e6-b7c6-e6a143b6d98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_search_button</value>
      <webElementGuid>bc7cafb2-4f53-44e3-940e-650b71f4bc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>12d53b22-de75-4ea3-84d6-376b72eae5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b23523cc-951c-4c98-bdf9-8194b7b9b9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_search_button&quot;)</value>
      <webElementGuid>07d9d59b-7589-4486-91c8-6a651f3caa7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js_search_button']</value>
      <webElementGuid>1c34add3-6927-4795-8a03-efdfcb7000e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-search']/label/button</value>
      <webElementGuid>1704dddb-9486-48e0-bf74-fc54d7bc12a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>958311e8-3e5b-42cf-a828-5a7ed1cb8657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'js_search_button' and @type = 'submit']</value>
      <webElementGuid>827b8776-a32b-4918-9169-b118b1939d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
