<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Finalizar mi compra</name>
   <tag></tag>
   <elementGuidId>9c76e98e-1f21-4981-a907-8ccc06706b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lastInTheForm123']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lastInTheForm123</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Finalizar mi compra&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18a14e54-ab12-4da5-86fc-17fe888ac78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block</value>
      <webElementGuid>e59ae195-43c5-439e-9633-1a2f5a68d19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cfea5bcf-a31c-4443-84b4-530b258eb8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ExpressDataLayerPago(); </value>
      <webElementGuid>649018ee-b818-4551-91b4-f2b1444da627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastInTheForm123</value>
      <webElementGuid>197a2c13-45f5-4dd3-a4c4-9a3a0a117b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Finalizar mi compra
                        </value>
      <webElementGuid>7e15cb70-1f1d-4f22-8b6d-dd049056aece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastInTheForm123&quot;)</value>
      <webElementGuid>a243d0f5-2464-4a66-8aa5-0f918df30b20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='lastInTheForm123']</value>
      <webElementGuid>30a6a254-3587-4f6a-94a1-279d493f3306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lastInTheForm123F']/button</value>
      <webElementGuid>ca605d0a-711c-45bf-9c97-1773cb9d1ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='antes de realizar el pago.'])[1]/following::button[1]</value>
      <webElementGuid>28a68f5f-b2f5-4c68-8d14-3e8ba8d4fa18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aquí'])[2]/preceding::button[1]</value>
      <webElementGuid>185b13e5-6f2f-4510-8922-0a1f8525c592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Finalizar mi compra']/parent::*</value>
      <webElementGuid>06a9bb36-2a2f-466f-a8b2-0ef1602d27f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>e06277dd-34c8-4905-a032-695bd7d8e267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'lastInTheForm123' and (text() = '
                            Finalizar mi compra
                        ' or . = '
                            Finalizar mi compra
                        ')]</value>
      <webElementGuid>14a4d52e-bd2b-4140-bb9d-b2f9c7678d1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
