<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__betweenStreet2</name>
   <tag></tag>
   <elementGuidId>78c0f53d-814b-4fc9-85c6-830d426ef3f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='betweenStreet2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#betweenStreet2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Entre que calles se encuentra tu domicilio&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7089ff06-71d8-43ac-a1ec-829eb9052cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>betweenStreet2</value>
      <webElementGuid>bb923810-1497-4aac-bc45-69e8a21cb655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>betweenStreet2</value>
      <webElementGuid>68d2ae4c-b466-420c-82fe-5763a66096ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text form-control</value>
      <webElementGuid>482632be-b85a-4c86-b373-8e571d79a0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (!window.__cfRLUnblockHandlers) return false; return charSpecial(event)</value>
      <webElementGuid>850bdd4c-14b3-4049-aab2-aa726639d29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78aa7150-1765-47b0-89bf-3295e2f898f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>--</value>
      <webElementGuid>547a280f-9f69-4c5b-a5ce-aa17444d40d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;betweenStreet2&quot;)</value>
      <webElementGuid>31ed427e-4dc4-4419-b592-ae0292ba2edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='betweenStreet2']</value>
      <webElementGuid>14dacb52-92c3-431d-8f10-e1e3b2892b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i18nAddressForm']/div/div[3]/div[11]/div/div/input</value>
      <webElementGuid>fbe3e2cd-c489-45dd-b01b-4bf8304e80af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>28304f48-f18c-4cbb-87e5-00af3556d8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'betweenStreet2' and @name = 'betweenStreet2' and @type = 'text']</value>
      <webElementGuid>28a5472f-3659-470c-8de5-c6b1cbf1a44d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
