<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifica tu ubicacin_saveAddressInMyA_91c621</name>
   <tag></tag>
   <elementGuidId>7e086aa8-5ca2-4a7e-93a2-9a07c776a676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saveAddressInMyAddressBook']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saveAddressInMyAddressBook</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Guardar esta dirección&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b7ef90e-90da-4f4e-92ba-8b4eb07cd2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveAddressInMyAddressBook</value>
      <webElementGuid>490785cc-a124-4d05-bdfa-1065cf757810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>saveInAddressBook</value>
      <webElementGuid>63378b6b-1bae-4179-96a1-d5f0404cd97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputcss</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>294a9682-0c6d-4ee1-a2a8-708dcd056611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e258d7b0-f7f2-4573-b413-486eb5e2db10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a2e2789-be0b-4a55-b73d-9e9fe54cddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveAddressInMyAddressBook&quot;)</value>
      <webElementGuid>bfab74ba-ee57-427d-9eb6-c0ec936f3619</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saveAddressInMyAddressBook']</value>
      <webElementGuid>6520968d-b051-4e08-b95a-4d22c61044e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i18nAddressForm']/div/div[3]/div[14]/div[3]/div/label/input</value>
      <webElementGuid>2f4b18ac-0bef-46e4-b2be-30a95aa66dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>f131b69e-3093-4370-b712-39f31863a3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'saveAddressInMyAddressBook' and @name = 'saveInAddressBook' and @type = 'checkbox']</value>
      <webElementGuid>99297985-04d6-4d28-a50e-f1209bf516c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
