<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pago con Tarjeta Dbito Crdito_paypos</name>
   <tag></tag>
   <elementGuidId>1f63fef5-06b5-401f-9d96-26773b81b011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paypos']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paypos</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Pago en tienda&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5983cd80-f47c-4ad7-8268-452a39a6a85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d5fa8c6c-1d59-45fe-90d7-29733dd63794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paypos</value>
      <webElementGuid>b3e025d5-a6fd-4bda-9aff-0462a3bd9cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name-radio-payment</value>
      <webElementGuid>c0ced52c-0b9a-4328-a630-c43e5516eb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paymentMethod-button</value>
      <webElementGuid>e3c51271-0d5e-4d58-97f7-03b64e73e8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paypos&quot;)</value>
      <webElementGuid>489aace1-0aae-4674-8ec8-a6ef2717be31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paypos']</value>
      <webElementGuid>c67f6fb9-bc31-4b4f-884b-29c89d06ed67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='label_paypos']/input</value>
      <webElementGuid>906690d5-f10f-4629-b3ca-9d1485626e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/label/input</value>
      <webElementGuid>e2dddd96-a5e3-4411-bf54-df93b0d2299b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'paypos' and @name = 'name-radio-payment']</value>
      <webElementGuid>92d15936-cc33-47f0-ab05-eb617c53fd2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
