<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha de nacimiento (ddmmaaaa)_input-_e8c017</name>
   <tag></tag>
   <elementGuidId>b06f1bc1-ddf1-4bf9-b197-906cc711306b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-birthday-gs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-birthday-gs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#input-birthday-gs</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3579c6d5-4d17-47d8-b990-c46569cbd0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-birthday-gs</value>
      <webElementGuid>ed771c22-a71c-4112-aba7-feda662b82b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>birthday-input</value>
      <webElementGuid>df1c91a2-90c0-41c5-900e-a539fde99fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2b687f99-6e16-435e-b898-7bebbc8f0abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday-gs</value>
      <webElementGuid>97680b41-2b0d-4fd0-b8f5-61bd5c14a927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(0[1-9]|1[012])[-/.](0[1-9]|[12][0-9]|3[01])[-/.](19|20)\d\d$</value>
      <webElementGuid>5d9e91ec-eb0d-4ae3-ad95-d1df4967f669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-birthday-gs&quot;)</value>
      <webElementGuid>10cb09c8-0127-4b34-9f6f-75ba7b4f27c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-birthday-gs']</value>
      <webElementGuid>c80d1fa6-c082-4d2e-929a-5e739fa6ef60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='popup_date_gs']/div[2]/div/div/input)[3]</value>
      <webElementGuid>32f7be63-fb12-47b1-b4bf-cadcfcb79aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>114c903f-0115-4198-92ad-d4352cd6dfe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-birthday-gs' and @name = 'birthday-gs']</value>
      <webElementGuid>129b48e3-0bdc-4459-8e18-1aa6790f1411</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
