<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Marca</name>
   <tag></tag>
   <elementGuidId>41cc374f-ce7a-42c4-99cf-6954ebf0da66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.facet__name-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product__facet']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1422cfff-5e34-4718-bfb5-365fdb1e8565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>facet__name-txt</value>
      <webElementGuid>35f0ec80-f5ab-4fe1-b930-de0e4110b888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Marca</value>
      <webElementGuid>fc133d8f-ee4e-41ca-a69d-3c8529b28b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filtrar-menu_dsk&quot;)/div[@id=&quot;product__facet&quot;]/div[@class=&quot;facet js-facet facet-cnt-Marca&quot;]/div[@class=&quot;facet__name js-facet-name&quot;]/div[@class=&quot;facet__name-txt&quot;]</value>
      <webElementGuid>7ef339cd-3bbc-4b9d-a515-f44c73fee8df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product__facet']/div/div/div</value>
      <webElementGuid>3ae1fb55-ed6a-4433-a504-bd91cdfb7b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtros'])[1]/following::div[7]</value>
      <webElementGuid>9daaffe2-ec8f-4946-ac48-3ebed072f33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.officedepot.com.mx'])[2]/following::div[65]</value>
      <webElementGuid>532d8779-f372-40a7-8120-9144650dc00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::div[1]</value>
      <webElementGuid>864826fd-90b1-486a-acfc-e5bd7cb5ad79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACER'])[1]/preceding::div[2]</value>
      <webElementGuid>d388a676-cb28-443a-9a0a-c805e8fff933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marca']/parent::*</value>
      <webElementGuid>7d216422-99fc-4f3d-8689-136d60f78074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>a85b9efc-3f48-42d6-8873-3fad7831fd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
				Marca' or . = '
				Marca')]</value>
      <webElementGuid>2fe6e157-dba5-4466-9b09-a4e7f353f6a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
