<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ACER_facet__list__mark</name>
   <tag></tag>
   <elementGuidId>8e1ab915-d825-4802-ab18-bad699b6b08e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_faceta_brand']/li/form/label/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.facet__list__mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lista_faceta_brand_dsk label >> internal:has-text=&quot;ACER&quot;i >> span >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55cf9f0c-2ef5-4428-bc73-1068b63d805a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>facet__list__mark</value>
      <webElementGuid>b7f9c01c-4141-4bf9-8a55-8478a576a137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lista_faceta_brand_dsk&quot;)/div[@id=&quot;div_faceta_brand&quot;]/li[1]/form[1]/label[1]/span[@class=&quot;facet__list__label&quot;]/span[@class=&quot;facet__list__mark&quot;]</value>
      <webElementGuid>24ef6521-46d2-4f6d-ba4b-160d8ae3c5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_faceta_brand']/li/form/label/span/span</value>
      <webElementGuid>f1851634-86fd-41fb-9ca0-b3e581e1ed10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/label/span/span</value>
      <webElementGuid>6c683573-3445-4a84-bc5f-2a28e308114a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
